# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Aula1_2017/Nexys4_Master.xdc

# Block Designs: bd/memdis/memdis.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memdis || ORIG_REF_NAME==memdis}]

# IP: bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/memdis_FirstBlock_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memdis_FirstBlock_wrapper_0_0 || ORIG_REF_NAME==memdis_FirstBlock_wrapper_0_0}]

# IP: bd/memdis/ip/memdis_blk_mem_gen_0_0/memdis_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==memdis_blk_mem_gen_0_0 || ORIG_REF_NAME==memdis_blk_mem_gen_0_0}]

# XDC: bd/memdis/memdis_ooc.xdc
