# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Test_teorico/Test_teorico.cache/wt [current_project]
set_property parent.project_path C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Test_teorico/Test_teorico.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Test_teorico/Test_teorico.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Test_teorico/Test_teorico.srcs/sources_1/new/test.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc]


synth_design -top test -part xc7a100tcsg324-1


write_checkpoint -force -noxdef test.dcp

catch { report_utilization -file test_utilization_synth.rpt -pb test_utilization_synth.pb }
