# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'design1_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'design1_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_1_sdk/Ex6_1_sdk.srcs/sources_1/bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
