# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc

# Block Designs: bd/vlock_design/vlock_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design || ORIG_REF_NAME==vlock_design}]

# IP: bd/vlock_design/ip/vlock_design_EightDispControl_0_0/vlock_design_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_EightDispControl_0_0 || ORIG_REF_NAME==vlock_design_EightDispControl_0_0}]

# IP: bd/vlock_design/ip/vlock_design_BinToBCD16_0_0/vlock_design_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_BinToBCD16_0_0 || ORIG_REF_NAME==vlock_design_BinToBCD16_0_0}]

# IP: bd/vlock_design/ip/vlock_design_xlconstant_0_0/vlock_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_xlconstant_0_0 || ORIG_REF_NAME==vlock_design_xlconstant_0_0}]

# IP: bd/vlock_design/ip/vlock_design_blk_mem_gen_0_0/vlock_design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_blk_mem_gen_0_0 || ORIG_REF_NAME==vlock_design_blk_mem_gen_0_0}]

# IP: bd/vlock_design/ip/vlock_design_c_counter_binary_0_0/vlock_design_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_c_counter_binary_0_0 || ORIG_REF_NAME==vlock_design_c_counter_binary_0_0}]

# IP: bd/vlock_design/ip/vlock_design_ClockDivider_0_1/vlock_design_ClockDivider_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_ClockDivider_0_1 || ORIG_REF_NAME==vlock_design_ClockDivider_0_1}]

# IP: bd/vlock_design/ip/vlock_design_xlconstant_2_0/vlock_design_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vlock_design_xlconstant_2_0 || ORIG_REF_NAME==vlock_design_xlconstant_2_0}]

# XDC: bd/vlock_design/vlock_design_ooc.xdc
