# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_2/Ex6_2.srcs/sources_1/bd/Dezign1/ip/Dezign1_ilmb_bram_if_cntlr_0/Dezign1_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Dezign1_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_2/Ex6_2.srcs/sources_1/bd/Dezign1/ip/Dezign1_ilmb_bram_if_cntlr_0/Dezign1_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dezign1_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_2/Ex6_2.srcs/sources_1/bd/Dezign1/ip/Dezign1_ilmb_bram_if_cntlr_0/Dezign1_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Dezign1_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Ex6_2/Ex6_2.srcs/sources_1/bd/Dezign1/ip/Dezign1_ilmb_bram_if_cntlr_0/Dezign1_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Dezign1_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
