# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Not_working/Nexys4_Master.xdc

# Block Designs: bd/ex2/ex2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2 || ORIG_REF_NAME==ex2}]

# IP: bd/ex2/ip/ex2_maxdivider_0_0/ex2_maxdivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_maxdivider_0_0 || ORIG_REF_NAME==ex2_maxdivider_0_0}]

# IP: bd/ex2/ip/ex2_BinToBCD16_0_0/ex2_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_BinToBCD16_0_0 || ORIG_REF_NAME==ex2_BinToBCD16_0_0}]

# IP: bd/ex2/ip/ex2_EightDispControl_0_0/ex2_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_EightDispControl_0_0 || ORIG_REF_NAME==ex2_EightDispControl_0_0}]

# IP: bd/ex2/ip/ex2_xlconstant_0_0/ex2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_xlconstant_0_0 || ORIG_REF_NAME==ex2_xlconstant_0_0}]

# IP: bd/ex2/ip/ex2_xlconstant_1_0/ex2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_xlconstant_1_0 || ORIG_REF_NAME==ex2_xlconstant_1_0}]

# IP: bd/ex2/ip/ex2_clockdivider_0_0/ex2_clockdivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_clockdivider_0_0 || ORIG_REF_NAME==ex2_clockdivider_0_0}]

# XDC: bd/ex2/ex2_ooc.xdc
