# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/design1_disp32bits_wrapper_0_0.xci
# IP: The module: 'design1_disp32bits_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_2/disp32bits_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_2 || ORIG_REF_NAME==disp32bits_xlslice_0_2}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_3/disp32bits_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_3 || ORIG_REF_NAME==disp32bits_xlslice_0_3}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_4/disp32bits_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_4 || ORIG_REF_NAME==disp32bits_xlslice_0_4}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_5/disp32bits_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_5 || ORIG_REF_NAME==disp32bits_xlslice_0_5}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_7/disp32bits_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_7 || ORIG_REF_NAME==disp32bits_xlslice_0_7}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_8/disp32bits_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_8 || ORIG_REF_NAME==disp32bits_xlslice_0_8}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_6_0/disp32bits_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_0 || ORIG_REF_NAME==disp32bits_xlslice_6_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_7_0/disp32bits_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_0 || ORIG_REF_NAME==disp32bits_xlslice_7_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_9/disp32bits_xlslice_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_9 || ORIG_REF_NAME==disp32bits_xlslice_0_9}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_3_2/disp32bits_xlslice_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_3_2 || ORIG_REF_NAME==disp32bits_xlslice_3_2}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_6_1/disp32bits_xlslice_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_1 || ORIG_REF_NAME==disp32bits_xlslice_6_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_7_1/disp32bits_xlslice_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_1 || ORIG_REF_NAME==disp32bits_xlslice_7_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_8_0/disp32bits_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_8_0 || ORIG_REF_NAME==disp32bits_xlslice_8_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_9_0/disp32bits_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_9_0 || ORIG_REF_NAME==disp32bits_xlslice_9_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_clockdivider_0_1/disp32bits_clockdivider_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_clockdivider_0_1 || ORIG_REF_NAME==disp32bits_clockdivider_0_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_EightDispControl_0_1/disp32bits_EightDispControl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_EightDispControl_0_1 || ORIG_REF_NAME==disp32bits_EightDispControl_0_1}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_disp32bits_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/32bitstodisp.srcs/sources_1/bd/disp32bits/disp32bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_disp32bits_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_ooc.xdc

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/design1_disp32bits_wrapper_0_0.xci
# IP: The module: 'design1_disp32bits_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_2/disp32bits_xlslice_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_2 || ORIG_REF_NAME==disp32bits_xlslice_0_2}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_3/disp32bits_xlslice_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_3 || ORIG_REF_NAME==disp32bits_xlslice_0_3}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_4/disp32bits_xlslice_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_4 || ORIG_REF_NAME==disp32bits_xlslice_0_4}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_5/disp32bits_xlslice_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_5 || ORIG_REF_NAME==disp32bits_xlslice_0_5}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_7/disp32bits_xlslice_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_7 || ORIG_REF_NAME==disp32bits_xlslice_0_7}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_8/disp32bits_xlslice_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_8 || ORIG_REF_NAME==disp32bits_xlslice_0_8}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_6_0/disp32bits_xlslice_6_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_0 || ORIG_REF_NAME==disp32bits_xlslice_6_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_7_0/disp32bits_xlslice_7_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_0 || ORIG_REF_NAME==disp32bits_xlslice_7_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_0_9/disp32bits_xlslice_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_9 || ORIG_REF_NAME==disp32bits_xlslice_0_9}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_3_2/disp32bits_xlslice_3_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_3_2 || ORIG_REF_NAME==disp32bits_xlslice_3_2}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_6_1/disp32bits_xlslice_6_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_1 || ORIG_REF_NAME==disp32bits_xlslice_6_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_7_1/disp32bits_xlslice_7_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_1 || ORIG_REF_NAME==disp32bits_xlslice_7_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_8_0/disp32bits_xlslice_8_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_8_0 || ORIG_REF_NAME==disp32bits_xlslice_8_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_xlslice_9_0/disp32bits_xlslice_9_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_9_0 || ORIG_REF_NAME==disp32bits_xlslice_9_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_clockdivider_0_1/disp32bits_clockdivider_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_clockdivider_0_1 || ORIG_REF_NAME==disp32bits_clockdivider_0_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_EightDispControl_0_1/disp32bits_EightDispControl_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_EightDispControl_0_1 || ORIG_REF_NAME==disp32bits_EightDispControl_0_1}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_disp32bits_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/32bitstodisp.srcs/sources_1/bd/disp32bits/disp32bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_disp32bits_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_disp32bits_wrapper_0_0/src/disp32bits_ooc.xdc
