# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/memdis_FirstBlock_wrapper_0_0.xci
# IP: The module: 'memdis_FirstBlock_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_EightDispControl_0_0/FirstBlock_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_EightDispControl_0_0 || ORIG_REF_NAME==FirstBlock_EightDispControl_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_BinToBCD16_0_0/FirstBlock_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_BinToBCD16_0_0 || ORIG_REF_NAME==FirstBlock_BinToBCD16_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_xlconstant_0_0/FirstBlock_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_0_0 || ORIG_REF_NAME==FirstBlock_xlconstant_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_xlconstant_1_0/FirstBlock_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_1_0 || ORIG_REF_NAME==FirstBlock_xlconstant_1_0}]

# XDC: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/constrs_1/imports/Aula1_2017/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'memdis_FirstBlock_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/FirstBlock_ooc.xdc

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/memdis_FirstBlock_wrapper_0_0.xci
# IP: The module: 'memdis_FirstBlock_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_EightDispControl_0_0/FirstBlock_EightDispControl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_EightDispControl_0_0 || ORIG_REF_NAME==FirstBlock_EightDispControl_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_BinToBCD16_0_0/FirstBlock_BinToBCD16_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_BinToBCD16_0_0 || ORIG_REF_NAME==FirstBlock_BinToBCD16_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_xlconstant_0_0/FirstBlock_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_0_0 || ORIG_REF_NAME==FirstBlock_xlconstant_0_0}]

# IP: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/ip/FirstBlock_xlconstant_1_0/FirstBlock_xlconstant_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_1_0 || ORIG_REF_NAME==FirstBlock_xlconstant_1_0}]

# XDC: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/constrs_1/imports/Aula1_2017/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'memdis_FirstBlock_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: k:/CRExamples2017/AT5/Repository/MemoryDisp2017/MemoryDisp2017.srcs/sources_1/bd/memdis/ip/memdis_FirstBlock_wrapper_0_0/sources_1/bd/FirstBlock/FirstBlock_ooc.xdc
