# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0.xci
# IP: The module: 'desig1_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0.xci
# IP: The module: 'desig1_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/ex1/ex1.srcs/sources_1/bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'desig1_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
