# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_blk_mem_gen_0_0_1/design1_blk_mem_gen_0_0.xci
# IP: The module: 'design1_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_blk_mem_gen_0_0_1/design1_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_blk_mem_gen_0_0_1/design1_blk_mem_gen_0_0.xci
# IP: The module: 'design1_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/ex1/ex1.srcs/sources_1/bd/design1/ip/design1_blk_mem_gen_0_0_1/design1_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
