# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Aula1_2017/Nexys4_Master.xdc

# Block Designs: bd/FirstBlock/FirstBlock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock || ORIG_REF_NAME==FirstBlock}]

# IP: bd/FirstBlock/ip/FirstBlock_EightDispControl_0_0/FirstBlock_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_EightDispControl_0_0 || ORIG_REF_NAME==FirstBlock_EightDispControl_0_0}]

# IP: bd/FirstBlock/ip/FirstBlock_BinToBCD16_0_0/FirstBlock_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_BinToBCD16_0_0 || ORIG_REF_NAME==FirstBlock_BinToBCD16_0_0}]

# IP: bd/FirstBlock/ip/FirstBlock_xlconstant_0_0/FirstBlock_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_0_0 || ORIG_REF_NAME==FirstBlock_xlconstant_0_0}]

# IP: bd/FirstBlock/ip/FirstBlock_xlconstant_1_0/FirstBlock_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FirstBlock_xlconstant_1_0 || ORIG_REF_NAME==FirstBlock_xlconstant_1_0}]

# XDC: bd/FirstBlock/FirstBlock_ooc.xdc
