# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.cache/wt [current_project]
set_property parent.project_path K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  k:/crexamples2017/at5/repository/firstblockdes2017/firstblockdes2017.srcs
  k:/CRExamples2017/AT5/Repository/Repository
} [current_project]
set_property ip_output_repo k:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/sources_1/bd/FirstBlock/hdl/FirstBlock_wrapper.vhd
add_files K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/sources_1/bd/FirstBlock/FirstBlock.bd
set_property used_in_implementation false [get_files -all K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/sources_1/bd/FirstBlock/FirstBlock_ooc.xdc]
set_property is_locked true [get_files K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/sources_1/bd/FirstBlock/FirstBlock.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/constrs_1/imports/Aula1_2017/Nexys4_Master.xdc
set_property used_in_implementation false [get_files K:/CRExamples2017/AT5/Repository/FirstBlockDes2017/FirstBlockDes2017.srcs/constrs_1/imports/Aula1_2017/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top FirstBlock_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef FirstBlock_wrapper.dcp

catch { report_utilization -file FirstBlock_wrapper_utilization_synth.rpt -pb FirstBlock_wrapper_utilization_synth.pb }
