# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.cache/wt [current_project]
set_property parent.project_path C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame [current_project]
set_property ip_output_repo c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/coe_Exam.coe
read_vhdl -library xil_defaultlib C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/hdl/desigf_wrapper.vhd
add_files C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/desigf.bd
set_property used_in_implementation false [get_files -all c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/ip/desigf_ClockDivider_0_0/constrs_1/imports/Exame/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/ip/desigf_Control_1_0_0/constrs_1/imports/Exame/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/ip/desigf_blk_mem_gen_0_0/desigf_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/desigf_ooc.xdc]
set_property is_locked true [get_files C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Exame/Toplevel/Toplevel.srcs/sources_1/bd/desigf/desigf.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top desigf_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef desigf_wrapper.dcp

catch { report_utilization -file desigf_wrapper_utilization_synth.rpt -pb desigf_wrapper_utilization_synth.pb }
