# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/desigf/desigf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf || ORIG_REF_NAME==desigf}]

# IP: bd/desigf/ip/desigf_ClockDivider_0_0/desigf_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_ClockDivider_0_0 || ORIG_REF_NAME==desigf_ClockDivider_0_0}]

# IP: bd/desigf/ip/desigf_Sort_0_0/desigf_Sort_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_Sort_0_0 || ORIG_REF_NAME==desigf_Sort_0_0}]

# IP: bd/desigf/ip/desigf_EightDispControl_0_0/desigf_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_EightDispControl_0_0 || ORIG_REF_NAME==desigf_EightDispControl_0_0}]

# IP: bd/desigf/ip/desigf_Control_1_0_0/desigf_Control_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_Control_1_0_0 || ORIG_REF_NAME==desigf_Control_1_0_0}]

# IP: bd/desigf/ip/desigf_blk_mem_gen_0_0/desigf_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_blk_mem_gen_0_0 || ORIG_REF_NAME==desigf_blk_mem_gen_0_0}]

# IP: bd/desigf/ip/desigf_xlconstant_0_0/desigf_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desigf_xlconstant_0_0 || ORIG_REF_NAME==desigf_xlconstant_0_0}]

# XDC: bd/desigf/desigf_ooc.xdc
