# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Nexys4_Master.xdc

# Block Designs: bd/design1/design1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1 || ORIG_REF_NAME==design1}]

# IP: bd/design1/ip/design1_blk_mem_gen_0_0_1/design1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_blk_mem_gen_0_0 || ORIG_REF_NAME==design1_blk_mem_gen_0_0}]

# IP: bd/design1/ip/design1_disp32bits_wrapper_0_0/design1_disp32bits_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_disp32bits_wrapper_0_0 || ORIG_REF_NAME==design1_disp32bits_wrapper_0_0}]

# XDC: bd/design1/design1_ooc.xdc
