# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc

# Block Designs: bd/desinf/desinf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf || ORIG_REF_NAME==desinf}]

# IP: bd/desinf/ip/desinf_blk_mem_gen_0_0_1/desinf_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_blk_mem_gen_0_0 || ORIG_REF_NAME==desinf_blk_mem_gen_0_0}]

# IP: bd/desinf/ip/desinf_clockdivider_0_0/desinf_clockdivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_clockdivider_0_0 || ORIG_REF_NAME==desinf_clockdivider_0_0}]

# IP: bd/desinf/ip/desinf_BinToBCD16_0_0/desinf_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_BinToBCD16_0_0 || ORIG_REF_NAME==desinf_BinToBCD16_0_0}]

# IP: bd/desinf/ip/desinf_xlconcat_0_0/desinf_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_xlconcat_0_0 || ORIG_REF_NAME==desinf_xlconcat_0_0}]

# IP: bd/desinf/ip/desinf_xlconstant_0_0/desinf_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_xlconstant_0_0 || ORIG_REF_NAME==desinf_xlconstant_0_0}]

# IP: bd/desinf/ip/desinf_xlconstant_1_0/desinf_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_xlconstant_1_0 || ORIG_REF_NAME==desinf_xlconstant_1_0}]

# IP: bd/desinf/ip/desinf_BinToBCD16_1_0/desinf_BinToBCD16_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_BinToBCD16_1_0 || ORIG_REF_NAME==desinf_BinToBCD16_1_0}]

# IP: bd/desinf/ip/desinf_xlconstant_2_0/desinf_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_xlconstant_2_0 || ORIG_REF_NAME==desinf_xlconstant_2_0}]

# IP: bd/desinf/ip/desinf_xlconcat_1_0/desinf_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_xlconcat_1_0 || ORIG_REF_NAME==desinf_xlconcat_1_0}]

# IP: bd/desinf/ip/desinf_EightDispControl_0_0/desinf_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_EightDispControl_0_0 || ORIG_REF_NAME==desinf_EightDispControl_0_0}]

# IP: bd/desinf/ip/desinf_counter_0_0/desinf_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desinf_counter_0_0 || ORIG_REF_NAME==desinf_counter_0_0}]

# XDC: bd/desinf/desinf_ooc.xdc
