# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Nexys4_Master.xdc

# Block Designs: bd/Find1000/Find1000.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000 || ORIG_REF_NAME==Find1000}]

# IP: bd/Find1000/ip/Find1000_clockdivider_0_0_1/Find1000_clockdivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_clockdivider_0_0 || ORIG_REF_NAME==Find1000_clockdivider_0_0}]

# IP: bd/Find1000/ip/Find1000_Find1_0_0_1/Find1000_Find1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_Find1_0_0 || ORIG_REF_NAME==Find1000_Find1_0_0}]

# IP: bd/Find1000/ip/Find1000_BinToBCD16_0_0_1/Find1000_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_BinToBCD16_0_0 || ORIG_REF_NAME==Find1000_BinToBCD16_0_0}]

# IP: bd/Find1000/ip/Find1000_EightDispControl_0_0_1/Find1000_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_EightDispControl_0_0 || ORIG_REF_NAME==Find1000_EightDispControl_0_0}]

# IP: bd/Find1000/ip/Find1000_xlconstant_0_0_1/Find1000_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_xlconstant_0_0 || ORIG_REF_NAME==Find1000_xlconstant_0_0}]

# IP: bd/Find1000/ip/Find1000_xlconstant_1_0_1/Find1000_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_xlconstant_1_0 || ORIG_REF_NAME==Find1000_xlconstant_1_0}]

# IP: bd/Find1000/ip/Find1000_RandomGenerator_0_2/Find1000_RandomGenerator_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Find1000_RandomGenerator_0_2 || ORIG_REF_NAME==Find1000_RandomGenerator_0_2}]

# XDC: bd/Find1000/Find1000_ooc.xdc
