# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/design_1_maxdivider_0_0.xci
# IP: The module: 'design_1_maxdivider_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_BinToBCD16_0_0/design_1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BinToBCD16_0_0 || ORIG_REF_NAME==design_1_BinToBCD16_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_EightDispControl_0_0/design_1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_EightDispControl_0_0 || ORIG_REF_NAME==design_1_EightDispControl_0_0}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_maxdivider_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/design_1_maxdivider_0_0.xci
# IP: The module: 'design_1_maxdivider_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_BinToBCD16_0_0/design_1_BinToBCD16_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BinToBCD16_0_0 || ORIG_REF_NAME==design_1_BinToBCD16_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_EightDispControl_0_0/design_1_EightDispControl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_EightDispControl_0_0 || ORIG_REF_NAME==design_1_EightDispControl_0_0}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Lesson3.srcs/sources_1/bd/design_1/ip/design_1_maxdivider_0_0/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_maxdivider_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
