# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Nexys4_Master.xdc

# Block Designs: bd/ex_1/ex_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1 || ORIG_REF_NAME==ex_1}]

# IP: bd/ex_1/ip/ex_1_ex1_0_0/ex_1_ex1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1_ex1_0_0 || ORIG_REF_NAME==ex_1_ex1_0_0}]

# IP: bd/ex_1/ip/ex_1_BinToBCD16_0_0/ex_1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1_BinToBCD16_0_0 || ORIG_REF_NAME==ex_1_BinToBCD16_0_0}]

# IP: bd/ex_1/ip/ex_1_EightDispControl_0_0/ex_1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1_EightDispControl_0_0 || ORIG_REF_NAME==ex_1_EightDispControl_0_0}]

# IP: bd/ex_1/ip/ex_1_xlconstant_0_0/ex_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1_xlconstant_0_0 || ORIG_REF_NAME==ex_1_xlconstant_0_0}]

# IP: bd/ex_1/ip/ex_1_xlconstant_1_0/ex_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex_1_xlconstant_1_0 || ORIG_REF_NAME==ex_1_xlconstant_1_0}]

# XDC: bd/ex_1/ex_1_ooc.xdc
