# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc

# Block Designs: bd/Dezign1/Dezign1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1 || ORIG_REF_NAME==Dezign1}]

# IP: bd/Dezign1/ip/Dezign1_microblaze_0_0/Dezign1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_microblaze_0_0 || ORIG_REF_NAME==Dezign1_microblaze_0_0}]

# IP: bd/Dezign1/ip/Dezign1_dlmb_v10_0/Dezign1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_dlmb_v10_0 || ORIG_REF_NAME==Dezign1_dlmb_v10_0}]

# IP: bd/Dezign1/ip/Dezign1_ilmb_v10_0/Dezign1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_ilmb_v10_0 || ORIG_REF_NAME==Dezign1_ilmb_v10_0}]

# IP: bd/Dezign1/ip/Dezign1_dlmb_bram_if_cntlr_0/Dezign1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Dezign1_dlmb_bram_if_cntlr_0}]

# IP: bd/Dezign1/ip/Dezign1_ilmb_bram_if_cntlr_0/Dezign1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Dezign1_ilmb_bram_if_cntlr_0}]

# IP: bd/Dezign1/ip/Dezign1_lmb_bram_0/Dezign1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_lmb_bram_0 || ORIG_REF_NAME==Dezign1_lmb_bram_0}]

# IP: bd/Dezign1/ip/Dezign1_microblaze_0_axi_periph_0/Dezign1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Dezign1_microblaze_0_axi_periph_0}]

# IP: bd/Dezign1/ip/Dezign1_mdm_1_0/Dezign1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_mdm_1_0 || ORIG_REF_NAME==Dezign1_mdm_1_0}]

# IP: bd/Dezign1/ip/Dezign1_clk_wiz_1_0/Dezign1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_clk_wiz_1_0 || ORIG_REF_NAME==Dezign1_clk_wiz_1_0}]

# IP: bd/Dezign1/ip/Dezign1_rst_clk_wiz_1_100M_0/Dezign1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Dezign1_rst_clk_wiz_1_100M_0}]

# IP: bd/Dezign1/ip/Dezign1_axi_gpio_0_0/Dezign1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_axi_gpio_0_0 || ORIG_REF_NAME==Dezign1_axi_gpio_0_0}]

# IP: bd/Dezign1/ip/Dezign1_xbar_0/Dezign1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xbar_0 || ORIG_REF_NAME==Dezign1_xbar_0}]

# IP: bd/Dezign1/ip/Dezign1_xlslice_0_0/Dezign1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlslice_0_0 || ORIG_REF_NAME==Dezign1_xlslice_0_0}]

# IP: bd/Dezign1/ip/Dezign1_xlslice_0_1/Dezign1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlslice_0_1 || ORIG_REF_NAME==Dezign1_xlslice_0_1}]

# IP: bd/Dezign1/ip/Dezign1_xlslice_0_2/Dezign1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlslice_0_2 || ORIG_REF_NAME==Dezign1_xlslice_0_2}]

# IP: bd/Dezign1/ip/Dezign1_xlslice_0_3/Dezign1_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlslice_0_3 || ORIG_REF_NAME==Dezign1_xlslice_0_3}]

# IP: bd/Dezign1/ip/Dezign1_dist_mem_gen_0_0/Dezign1_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_dist_mem_gen_0_0 || ORIG_REF_NAME==Dezign1_dist_mem_gen_0_0}]

# IP: bd/Dezign1/ip/Dezign1_ClockDivider_0_0/Dezign1_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_ClockDivider_0_0 || ORIG_REF_NAME==Dezign1_ClockDivider_0_0}]

# IP: bd/Dezign1/ip/Dezign1_c_counter_binary_0_0/Dezign1_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_c_counter_binary_0_0 || ORIG_REF_NAME==Dezign1_c_counter_binary_0_0}]

# IP: bd/Dezign1/ip/Dezign1_BinToBCD16_0_0/Dezign1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_BinToBCD16_0_0 || ORIG_REF_NAME==Dezign1_BinToBCD16_0_0}]

# IP: bd/Dezign1/ip/Dezign1_xlconstant_0_0/Dezign1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlconstant_0_0 || ORIG_REF_NAME==Dezign1_xlconstant_0_0}]

# IP: bd/Dezign1/ip/Dezign1_EightDispControl_0_0/Dezign1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_EightDispControl_0_0 || ORIG_REF_NAME==Dezign1_EightDispControl_0_0}]

# IP: bd/Dezign1/ip/Dezign1_xlconstant_1_0/Dezign1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Dezign1_xlconstant_1_0 || ORIG_REF_NAME==Dezign1_xlconstant_1_0}]

# XDC: bd/Dezign1/Dezign1_ooc.xdc
