# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Nexys4_Master.xdc

# Block Designs: bd/swtodisplays/swtodisplays.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays || ORIG_REF_NAME==swtodisplays}]

# IP: bd/swtodisplays/ip/swtodisplays_EightDispControl_0_0/swtodisplays_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays_EightDispControl_0_0 || ORIG_REF_NAME==swtodisplays_EightDispControl_0_0}]

# IP: bd/swtodisplays/ip/swtodisplays_clockdivider_0_0/swtodisplays_clockdivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays_clockdivider_0_0 || ORIG_REF_NAME==swtodisplays_clockdivider_0_0}]

# IP: bd/swtodisplays/ip/swtodisplays_BinToBCD16_0_0/swtodisplays_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays_BinToBCD16_0_0 || ORIG_REF_NAME==swtodisplays_BinToBCD16_0_0}]

# IP: bd/swtodisplays/ip/swtodisplays_xlconstant_0_0/swtodisplays_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays_xlconstant_0_0 || ORIG_REF_NAME==swtodisplays_xlconstant_0_0}]

# IP: bd/swtodisplays/ip/swtodisplays_xlconstant_1_0/swtodisplays_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==swtodisplays_xlconstant_1_0 || ORIG_REF_NAME==swtodisplays_xlconstant_1_0}]

# XDC: bd/swtodisplays/swtodisplays_ooc.xdc
