# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Ex2/Ex2.srcs/sources_1/bd/ex2/ip/ex2_maxdivider_0_0/ex2_maxdivider_0_0.xci
# IP: The module: 'ex2_maxdivider_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Ex2/Ex2.srcs/sources_1/bd/ex2/ip/ex2_maxdivider_0_0/constrs_1/imports/Not_working/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_maxdivider_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Ex2/Ex2.srcs/sources_1/bd/ex2/ip/ex2_maxdivider_0_0/ex2_maxdivider_0_0.xci
# IP: The module: 'ex2_maxdivider_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson3/Ex2/Ex2.srcs/sources_1/bd/ex2/ip/ex2_maxdivider_0_0/constrs_1/imports/Not_working/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_maxdivider_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
