# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/Nexys4_Master.xdc

# Block Designs: bd/design1/design1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1 || ORIG_REF_NAME==design1}]

# IP: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_microblaze_0_0 || ORIG_REF_NAME==design1_microblaze_0_0}]

# IP: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_dlmb_v10_0 || ORIG_REF_NAME==design1_dlmb_v10_0}]

# IP: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ilmb_v10_0 || ORIG_REF_NAME==design1_ilmb_v10_0}]

# IP: bd/design1/ip/design1_dlmb_bram_if_cntlr_0/design1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design1_dlmb_bram_if_cntlr_0}]

# IP: bd/design1/ip/design1_ilmb_bram_if_cntlr_0/design1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design1_ilmb_bram_if_cntlr_0}]

# IP: bd/design1/ip/design1_lmb_bram_0/design1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_lmb_bram_0 || ORIG_REF_NAME==design1_lmb_bram_0}]

# IP: bd/design1/ip/design1_microblaze_0_axi_periph_0/design1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design1_microblaze_0_axi_periph_0}]

# IP: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_mdm_1_0 || ORIG_REF_NAME==design1_mdm_1_0}]

# IP: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}]

# IP: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}]

# IP: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}]

# IP: bd/design1/ip/design1_xbar_0/design1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xbar_0 || ORIG_REF_NAME==design1_xbar_0}]

# IP: bd/design1/ip/design1_blk_mem_gen_0_0/design1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_blk_mem_gen_0_0 || ORIG_REF_NAME==design1_blk_mem_gen_0_0}]

# IP: bd/design1/ip/design1_xlslice_0_0/design1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_0_0 || ORIG_REF_NAME==design1_xlslice_0_0}]

# IP: bd/design1/ip/design1_xlslice_1_0/design1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_0 || ORIG_REF_NAME==design1_xlslice_1_0}]

# IP: bd/design1/ip/design1_xlslice_1_1/design1_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_1 || ORIG_REF_NAME==design1_xlslice_1_1}]

# IP: bd/design1/ip/design1_xlslice_1_2/design1_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_2 || ORIG_REF_NAME==design1_xlslice_1_2}]

# IP: bd/design1/ip/design1_ClockDivider_0_0/design1_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ClockDivider_0_0 || ORIG_REF_NAME==design1_ClockDivider_0_0}]

# IP: bd/design1/ip/design1_Unroll_ROM_last_0_0/design1_Unroll_ROM_last_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_Unroll_ROM_last_0_0 || ORIG_REF_NAME==design1_Unroll_ROM_last_0_0}]

# IP: bd/design1/ip/design1_xlslice_3_0/design1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_3_0 || ORIG_REF_NAME==design1_xlslice_3_0}]

# IP: bd/design1/ip/design1_util_vector_logic_0_0/design1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_util_vector_logic_0_0 || ORIG_REF_NAME==design1_util_vector_logic_0_0}]

# IP: bd/design1/ip/design1_EightDispControl_0_0/design1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_EightDispControl_0_0 || ORIG_REF_NAME==design1_EightDispControl_0_0}]

# IP: bd/design1/ip/design1_Convert_10_8_to_8_10_FSM_0_0/design1_Convert_10_8_to_8_10_FSM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_Convert_10_8_to_8_10_FSM_0_0 || ORIG_REF_NAME==design1_Convert_10_8_to_8_10_FSM_0_0}]

# IP: bd/design1/ip/design1_blk_mem_gen_0_1/design1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_blk_mem_gen_0_1 || ORIG_REF_NAME==design1_blk_mem_gen_0_1}]

# IP: bd/design1/ip/design1_Hamming_weight_0_0/design1_Hamming_weight_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_Hamming_weight_0_0 || ORIG_REF_NAME==design1_Hamming_weight_0_0}]

# IP: bd/design1/ip/design1_VGA_for_block_0_0/design1_VGA_for_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_VGA_for_block_0_0 || ORIG_REF_NAME==design1_VGA_for_block_0_0}]

# IP: bd/design1/ip/design1_xlconcat_0_0/design1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlconcat_0_0 || ORIG_REF_NAME==design1_xlconcat_0_0}]

# IP: bd/design1/ip/design1_xlslice_1_3/design1_xlslice_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_3 || ORIG_REF_NAME==design1_xlslice_1_3}]

# IP: bd/design1/ip/design1_xlslice_1_4/design1_xlslice_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_4 || ORIG_REF_NAME==design1_xlslice_1_4}]

# IP: bd/design1/ip/design1_xlslice_3_1/design1_xlslice_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_3_1 || ORIG_REF_NAME==design1_xlslice_3_1}]

# IP: bd/design1/ip/design1_xlconstant_0_0/design1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlconstant_0_0 || ORIG_REF_NAME==design1_xlconstant_0_0}]

# IP: bd/design1/ip/design1_xlslice_4_0/design1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_4_0 || ORIG_REF_NAME==design1_xlslice_4_0}]

# IP: bd/design1/ip/design1_xlslice_4_1/design1_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_4_1 || ORIG_REF_NAME==design1_xlslice_4_1}]

# IP: bd/design1/ip/design1_axi_gpio_0_2/design1_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_2 || ORIG_REF_NAME==design1_axi_gpio_0_2}]

# IP: bd/design1/ip/design1_auto_pc_0/design1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_auto_pc_0 || ORIG_REF_NAME==design1_auto_pc_0}]

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_microblaze_0_0 || ORIG_REF_NAME==design1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_dlmb_v10_0 || ORIG_REF_NAME==design1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0_ooc.xdc

# XDC: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_ilmb_v10_0 || ORIG_REF_NAME==design1_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0_ooc.xdc

# XDC: bd/design1/ip/design1_dlmb_bram_if_cntlr_0/design1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design1/ip/design1_ilmb_bram_if_cntlr_0/design1_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design1/ip/design1_lmb_bram_0/design1_lmb_bram_0_ooc.xdc

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_mdm_1_0 || ORIG_REF_NAME==design1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0_ooc_trace.xdc

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0_ooc.xdc

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0_ooc.xdc

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_xbar_0/design1_xbar_0_ooc.xdc

# XDC: bd/design1/ip/design1_blk_mem_gen_0_0/design1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_ClockDivider_0_0/constrs_1/imports/Exame/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_ClockDivider_0_0 || ORIG_REF_NAME==design1_ClockDivider_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_Unroll_ROM_last_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_Unroll_ROM_last_0_0 || ORIG_REF_NAME==design1_Unroll_ROM_last_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_Convert_10_8_to_8_10_FSM_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_Convert_10_8_to_8_10_FSM_0_0 || ORIG_REF_NAME==design1_Convert_10_8_to_8_10_FSM_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_blk_mem_gen_0_1/design1_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/design1/ip/design1_Hamming_weight_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_Hamming_weight_0_0 || ORIG_REF_NAME==design1_Hamming_weight_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_axi_gpio_0_2/design1_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_2 || ORIG_REF_NAME==design1_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_axi_gpio_0_2/design1_axi_gpio_0_2_ooc.xdc

# XDC: bd/design1/ip/design1_axi_gpio_0_2/design1_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_2 || ORIG_REF_NAME==design1_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_auto_pc_0/design1_auto_pc_0_ooc.xdc

# XDC: bd/design1/design1_ooc.xdc
