# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/design_1_disp32bits_wrapper_0_2.xci
# IP: The module: 'design_1_disp32bits_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_0_0_1/disp32bits_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_0 || ORIG_REF_NAME==disp32bits_xlslice_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_1_0_1/disp32bits_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_1_0 || ORIG_REF_NAME==disp32bits_xlslice_1_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_2_0/disp32bits_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_2_0 || ORIG_REF_NAME==disp32bits_xlslice_2_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_3_0_1/disp32bits_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_3_0 || ORIG_REF_NAME==disp32bits_xlslice_3_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_4_0_1/disp32bits_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_4_0 || ORIG_REF_NAME==disp32bits_xlslice_4_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_5_0_1/disp32bits_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_5_0 || ORIG_REF_NAME==disp32bits_xlslice_5_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_6_0/disp32bits_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_0 || ORIG_REF_NAME==disp32bits_xlslice_6_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_7_0/disp32bits_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_0 || ORIG_REF_NAME==disp32bits_xlslice_7_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_8_0/disp32bits_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_8_0 || ORIG_REF_NAME==disp32bits_xlslice_8_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_9_0/disp32bits_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_9_0 || ORIG_REF_NAME==disp32bits_xlslice_9_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_EightDispControl_0_0_1/disp32bits_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_EightDispControl_0_0 || ORIG_REF_NAME==disp32bits_EightDispControl_0_0}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_disp32bits_wrapper_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/disp32bits_ooc.xdc

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/design_1_disp32bits_wrapper_0_2.xci
# IP: The module: 'design_1_disp32bits_wrapper_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_0_0_1/disp32bits_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_0_0 || ORIG_REF_NAME==disp32bits_xlslice_0_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_1_0_1/disp32bits_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_1_0 || ORIG_REF_NAME==disp32bits_xlslice_1_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_2_0/disp32bits_xlslice_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_2_0 || ORIG_REF_NAME==disp32bits_xlslice_2_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_3_0_1/disp32bits_xlslice_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_3_0 || ORIG_REF_NAME==disp32bits_xlslice_3_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_4_0_1/disp32bits_xlslice_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_4_0 || ORIG_REF_NAME==disp32bits_xlslice_4_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_5_0_1/disp32bits_xlslice_5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_5_0 || ORIG_REF_NAME==disp32bits_xlslice_5_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_6_0/disp32bits_xlslice_6_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_6_0 || ORIG_REF_NAME==disp32bits_xlslice_6_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_7_0/disp32bits_xlslice_7_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_7_0 || ORIG_REF_NAME==disp32bits_xlslice_7_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_8_0/disp32bits_xlslice_8_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_8_0 || ORIG_REF_NAME==disp32bits_xlslice_8_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_xlslice_9_0/disp32bits_xlslice_9_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_xlslice_9_0 || ORIG_REF_NAME==disp32bits_xlslice_9_0}]

# IP: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/ip/disp32bits_EightDispControl_0_0_1/disp32bits_EightDispControl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==disp32bits_EightDispControl_0_0 || ORIG_REF_NAME==disp32bits_EightDispControl_0_0}]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_disp32bits_wrapper_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson4/Ex2/Ex2.srcs/sources_1/bd/design_1/ip/design_1_disp32bits_wrapper_0_2/32bitstodisp.srcs/sources_1/bd/disp32bits/disp32bits_ooc.xdc
