# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.cache/wt [current_project]
set_property parent.project_path C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp
  c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Repository
} [current_project]
set_property ip_output_repo c:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.srcs/sources_1/bd/bit_32_disp/hdl/bit_32_disp_wrapper.v
add_files C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.srcs/sources_1/bd/bit_32_disp/bit_32_disp.bd
set_property used_in_implementation false [get_files -all C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.srcs/sources_1/bd/bit_32_disp/bit_32_disp_ooc.xdc]
set_property is_locked true [get_files C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Projecto_final/bit32disp/bit32disp.srcs/sources_1/bd/bit_32_disp/bit_32_disp.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/users/joao/desktop/cr/git/reconfigurable_computing/projecto_final/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/users/joao/desktop/cr/git/reconfigurable_computing/projecto_final/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top bit_32_disp_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef bit_32_disp_wrapper.dcp

catch { report_utilization -file bit_32_disp_wrapper_utilization_synth.rpt -pb bit_32_disp_wrapper_utilization_synth.pb }
