# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/joao/desktop/cr/git/reconfigurable_computing/projecto_final/Nexys4_Master.xdc

# Block Designs: bd/bit_32_disp/bit_32_disp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp || ORIG_REF_NAME==bit_32_disp}]

# IP: bd/bit_32_disp/ip/bit_32_disp_EightDispControl_0_0/bit_32_disp_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_EightDispControl_0_0 || ORIG_REF_NAME==bit_32_disp_EightDispControl_0_0}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_0/bit_32_disp_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_0 || ORIG_REF_NAME==bit_32_disp_xlslice_0_0}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_2/bit_32_disp_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_2 || ORIG_REF_NAME==bit_32_disp_xlslice_0_2}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_3/bit_32_disp_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_3 || ORIG_REF_NAME==bit_32_disp_xlslice_0_3}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_4/bit_32_disp_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_4 || ORIG_REF_NAME==bit_32_disp_xlslice_0_4}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_5/bit_32_disp_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_5 || ORIG_REF_NAME==bit_32_disp_xlslice_0_5}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_6/bit_32_disp_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_6 || ORIG_REF_NAME==bit_32_disp_xlslice_0_6}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_7/bit_32_disp_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_7 || ORIG_REF_NAME==bit_32_disp_xlslice_0_7}]

# IP: bd/bit_32_disp/ip/bit_32_disp_xlslice_0_8/bit_32_disp_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bit_32_disp_xlslice_0_8 || ORIG_REF_NAME==bit_32_disp_xlslice_0_8}]

# XDC: bd/bit_32_disp/bit_32_disp_ooc.xdc
