# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc

# Block Designs: bd/design1/design1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1 || ORIG_REF_NAME==design1}]

# IP: bd/design1/ip/design1_Find_Min_Max_0_0/design1_Find_Min_Max_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_Find_Min_Max_0_0 || ORIG_REF_NAME==design1_Find_Min_Max_0_0}]

# IP: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_microblaze_0_0 || ORIG_REF_NAME==design1_microblaze_0_0}]

# IP: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_dlmb_v10_0 || ORIG_REF_NAME==design1_dlmb_v10_0}]

# IP: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ilmb_v10_0 || ORIG_REF_NAME==design1_ilmb_v10_0}]

# IP: bd/design1/ip/design1_dlmb_bram_if_cntlr_0/design1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design1_dlmb_bram_if_cntlr_0}]

# IP: bd/design1/ip/design1_ilmb_bram_if_cntlr_0/design1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design1_ilmb_bram_if_cntlr_0}]

# IP: bd/design1/ip/design1_lmb_bram_0/design1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_lmb_bram_0 || ORIG_REF_NAME==design1_lmb_bram_0}]

# IP: bd/design1/ip/design1_microblaze_0_axi_periph_0/design1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design1_microblaze_0_axi_periph_0}]

# IP: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_mdm_1_0 || ORIG_REF_NAME==design1_mdm_1_0}]

# IP: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}]

# IP: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}]

# IP: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}]

# IP: bd/design1/ip/design1_xbar_0/design1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xbar_0 || ORIG_REF_NAME==design1_xbar_0}]

# IP: bd/design1/ip/design1_blk_mem_gen_0_0/design1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_blk_mem_gen_0_0 || ORIG_REF_NAME==design1_blk_mem_gen_0_0}]

# IP: bd/design1/ip/design1_xlslice_0_0/design1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_0_0 || ORIG_REF_NAME==design1_xlslice_0_0}]

# IP: bd/design1/ip/design1_xlslice_1_0/design1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_0 || ORIG_REF_NAME==design1_xlslice_1_0}]

# IP: bd/design1/ip/design1_xlslice_1_1/design1_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_1 || ORIG_REF_NAME==design1_xlslice_1_1}]

# IP: bd/design1/ip/design1_xlslice_1_2/design1_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlslice_1_2 || ORIG_REF_NAME==design1_xlslice_1_2}]

# IP: bd/design1/ip/design1_ClockDivider_0_0/design1_ClockDivider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_ClockDivider_0_0 || ORIG_REF_NAME==design1_ClockDivider_0_0}]

# IP: bd/design1/ip/design1_BinToBCD16_0_0/design1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_BinToBCD16_0_0 || ORIG_REF_NAME==design1_BinToBCD16_0_0}]

# IP: bd/design1/ip/design1_EightDispControl_0_0/design1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_EightDispControl_0_0 || ORIG_REF_NAME==design1_EightDispControl_0_0}]

# IP: bd/design1/ip/design1_xlconstant_0_0/design1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlconstant_0_0 || ORIG_REF_NAME==design1_xlconstant_0_0}]

# IP: bd/design1/ip/design1_c_counter_binary_0_1/design1_c_counter_binary_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_c_counter_binary_0_1 || ORIG_REF_NAME==design1_c_counter_binary_0_1}]

# IP: bd/design1/ip/design1_xlconstant_1_0/design1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design1_xlconstant_1_0 || ORIG_REF_NAME==design1_xlconstant_1_0}]

# XDC: bd/design1/ip/design1_Find_Min_Max_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_Find_Min_Max_0_0 || ORIG_REF_NAME==design1_Find_Min_Max_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_microblaze_0_0 || ORIG_REF_NAME==design1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/design1/ip/design1_microblaze_0_0/design1_microblaze_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_dlmb_v10_0 || ORIG_REF_NAME==design1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_dlmb_v10_0/design1_dlmb_v10_0_ooc.xdc

# XDC: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_ilmb_v10_0 || ORIG_REF_NAME==design1_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_ilmb_v10_0/design1_ilmb_v10_0_ooc.xdc

# XDC: bd/design1/ip/design1_dlmb_bram_if_cntlr_0/design1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design1/ip/design1_ilmb_bram_if_cntlr_0/design1_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/design1/ip/design1_lmb_bram_0/design1_lmb_bram_0_ooc.xdc

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_mdm_1_0 || ORIG_REF_NAME==design1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0_ooc_trace.xdc

# XDC: bd/design1/ip/design1_mdm_1_0/design1_mdm_1_0_ooc.xdc

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_clk_wiz_1_0 || ORIG_REF_NAME==design1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/design1/ip/design1_clk_wiz_1_0/design1_clk_wiz_1_0_ooc.xdc

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_rst_clk_wiz_1_100M_0/design1_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_axi_gpio_0_0/design1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_axi_gpio_0_0 || ORIG_REF_NAME==design1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_xbar_0/design1_xbar_0_ooc.xdc

# XDC: bd/design1/ip/design1_blk_mem_gen_0_0/design1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design1/ip/design1_ClockDivider_0_0/constrs_1/imports/Exame/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design1_ClockDivider_0_0 || ORIG_REF_NAME==design1_ClockDivider_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design1/ip/design1_c_counter_binary_0_1/design1_c_counter_binary_0_1_ooc.xdc

# XDC: bd/design1/design1_ooc.xdc
