# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Joao/Desktop/cr/Git/Reconfigurable_Computing/Lesson6/Nexys4_Master.xdc

# Block Designs: bd/desig1/desig1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1 || ORIG_REF_NAME==desig1}]

# IP: bd/desig1/ip/desig1_microblaze_0_1/desig1_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_microblaze_0_1 || ORIG_REF_NAME==desig1_microblaze_0_1}]

# IP: bd/desig1/ip/desig1_dlmb_v10_0/desig1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_dlmb_v10_0 || ORIG_REF_NAME==desig1_dlmb_v10_0}]

# IP: bd/desig1/ip/desig1_ilmb_v10_0/desig1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_ilmb_v10_0 || ORIG_REF_NAME==desig1_ilmb_v10_0}]

# IP: bd/desig1/ip/desig1_dlmb_bram_if_cntlr_0/desig1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==desig1_dlmb_bram_if_cntlr_0}]

# IP: bd/desig1/ip/desig1_ilmb_bram_if_cntlr_0/desig1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==desig1_ilmb_bram_if_cntlr_0}]

# IP: bd/desig1/ip/desig1_lmb_bram_0/desig1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_lmb_bram_0 || ORIG_REF_NAME==desig1_lmb_bram_0}]

# IP: bd/desig1/ip/desig1_microblaze_0_axi_periph_0/desig1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==desig1_microblaze_0_axi_periph_0}]

# IP: bd/desig1/ip/desig1_mdm_1_0/desig1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_mdm_1_0 || ORIG_REF_NAME==desig1_mdm_1_0}]

# IP: bd/desig1/ip/desig1_clk_wiz_1_0/desig1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_clk_wiz_1_0 || ORIG_REF_NAME==desig1_clk_wiz_1_0}]

# IP: bd/desig1/ip/desig1_rst_clk_wiz_1_100M_0/desig1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==desig1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==desig1_rst_clk_wiz_1_100M_0}]

# XDC: bd/desig1/desig1_ooc.xdc
